spring:
  config:
    activate:
      on-profile: local

  datasource:
    username: root
    password: 419914
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flow-task

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
    show-sql: true